# Site settings
title: Andrew's super duper test site
email: I-dont-like-no-spam@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my super cool test jekyll website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://croquagei.github.io" # the base hostname & protocol for your site
github_username:  croqugei

# Build settings
markdown: kramdown
