# Site settings
title: Andrew Davis
email: 
description: > # this means to ignore newlines until "baseurl:"
  A collection of my musings..or ramblings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://croquagei.github.io" # the base hostname & protocol for your site
github_username:  croqugei

# Build settings
markdown: kramdown
